-- VHDL Entity dinamico_drc_fast.FSM_dinamico_drc_fast_recon.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:55:19 06/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FSM_dinamico_drc_fast_recon IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic
   );

-- Declarations

END FSM_dinamico_drc_fast_recon ;

--
-- VHDL Architecture dinamico_drc_fast.FSM_dinamico_drc_fast_recon.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:55:19 06/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY dinamico_drc_fast;

ARCHITECTURE struct OF FSM_dinamico_drc_fast_recon IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico_out : std_logic;
   SIGNAL activa_led_w_aux    : std_logic;


   -- Component Declarations
   COMPONENT FSM_dinamico_drc_fast
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_drc_fast USE ENTITY dinamico_drc_fast.FSM_dinamico_drc_fast;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- purpose: loads din in dout
     -- type   : sequential
     -- inputs : clk, rst_n, d, en
     -- outputs: dout
     p_activa_led_e : process (clk, rst)
     begin
       if rising_edge(clk) then
         if rst = '1' then
           activa_led_e  <=  '1';
         else
            activa_led_e  <= '1';
         end if;
       end if;
     end process p_activa_led_e;
   
   

   -- HDL Embedded Text Block 2 eb2
   -- purpose: loads din in dout
     -- type   : sequential
     -- inputs : clk, rst_n, d, en
     -- outputs: dout
     p_activa_led_w : process (clk, rst)
     begin
       if rising_edge(clk) then
         if rst = '1' then
           activa_led_w  <= '1';
         else
            activa_led_w  <= activa_led_w_aux;
         end if;
       end if;
     end process p_activa_led_w;-- eb2 2                                        
   
   

   -- HDL Embedded Text Block 3 eb3
   -- purpose: loads din in dout
     -- type   : sequential
     -- inputs : clk, rst_n, d, en
     -- outputs: dout
     p_activa_dinamico : process (clk, rst)
     begin
       if rising_edge(clk) then
         if rst = '1' then
           activa_dinamico_out  <='1';
         else
            activa_dinamico_out <= activa_dinamico;
         end if;
       end if;
     end process p_activa_dinamico;-- eb2 2                                     
   
   
   


   -- Instance port mappings.
   i_FSM_dinamico_drc_fast : FSM_dinamico_drc_fast
      PORT MAP (
         activa_dinamico => activa_dinamico_out,
         clk             => clk,
         rst             => rst,
         activa_led_w    => activa_led_w_aux
      );

END struct;
