-- VHDL Entity todo_estado.black_box.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:38:04 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY black_box IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END black_box ;

--
-- VHDL Architecture todo_estado.black_box.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:38:03 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ARCHITECTURE struct OF black_box IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
