-- VHDL Entity todo_estado.top_estado.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:29:31 01/11/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY top_estado IS
   PORT( 
      clk        : IN     std_logic;
      rst        : IN     std_logic;
      start      : IN     std_logic;
      trigger_e  : IN     std_logic;
      trigger_w  : IN     std_logic;
      GPIO_LED_E : OUT    std_logic;
      GPIO_LED_N : OUT    std_logic;
      GPIO_LED_W : OUT    std_logic;
      O          : OUT    std_logic_vector (31 DOWNTO 0);
      busy       : OUT    std_logic;
      estado     : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END top_estado ;

--
-- VHDL Architecture todo_estado.top_estado.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:29:31 01/11/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_estatico;
LIBRARY todo;
LIBRARY todo_estado;

ARCHITECTURE struct OF top_estado IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;
   SIGNAL activa_led_e    : std_logic;
   SIGNAL activa_led_w    : std_logic;
   SIGNAL clk_100mz       : std_logic;
   SIGNAL enable_led      : std_logic;
   SIGNAL reset_dinamico  : std_logic;


   -- Component Declarations
   COMPONENT FSM_estatico
   PORT (
      clk          : IN     std_logic ;
      rst          : IN     std_logic ;
      start        : IN     std_logic ;
      activa_led_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT divisor_frecuencia
   PORT (
      clk_200mz : IN     std_logic;
      clk_100mz : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT registro_en
   PORT (
      clk    : IN     std_logic;
      d      : IN     std_logic;
      enable : IN     std_logic;
      rst    : IN     std_logic;
      q      : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT black_box
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic ;
      activa_led_w    : OUT    std_logic ;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT control_icap_estado
   PORT (
      clk                 : IN     std_logic ;
      rst                 : IN     std_logic ;
      trigger_e           : IN     std_logic ;
      trigger_w           : IN     std_logic ;
      O                   : OUT    std_logic_vector (31 DOWNTO 0);
      activa_dinamico_reg : OUT    std_logic ;
      busy                : OUT    std_logic ;
      enable_led_reg      : OUT    std_logic ;
      reset_dinamico_reg  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_estatico USE ENTITY FSM_estatico.FSM_estatico;
   FOR ALL : black_box USE ENTITY todo_estado.black_box;
   FOR ALL : control_icap_estado USE ENTITY todo_estado.control_icap_estado;
   FOR ALL : divisor_frecuencia USE ENTITY todo.divisor_frecuencia;
   FOR ALL : registro_en USE ENTITY todo.registro_en;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   i_FSM_estatico : FSM_estatico
      PORT MAP (
         clk          => clk,
         rst          => rst,
         start        => start,
         activa_led_n => GPIO_LED_N
      );
   i_divisor_frecuencia : divisor_frecuencia
      PORT MAP (
         clk_200mz => clk,
         clk_100mz => clk_100mz
      );
   i_reg_led_e : registro_en
      PORT MAP (
         clk    => clk,
         rst    => rst,
         d      => activa_led_e,
         enable => enable_led,
         q      => GPIO_LED_E
      );
   i_reg_led_w : registro_en
      PORT MAP (
         clk    => clk,
         rst    => rst,
         d      => activa_led_w,
         enable => enable_led,
         q      => GPIO_LED_W
      );
   i_black_box : black_box
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         reset_dinamico  => reset_dinamico,
         rst             => rst,
         activa_led_e    => activa_led_e,
         activa_led_w    => activa_led_w,
         estado          => estado
      );
   i_control_icap_estado : control_icap_estado
      PORT MAP (
         clk                 => clk_100mz,
         rst                 => rst,
         trigger_e           => trigger_e,
         trigger_w           => trigger_w,
         O                   => O,
         activa_dinamico_reg => activa_dinamico,
         busy                => busy,
         enable_led_reg      => enable_led,
         reset_dinamico_reg  => reset_dinamico
      );

END struct;
