-- VHDL Entity tb_dinamico_e.tb_FSM_dinamico_e.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 13:40:04 04/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_FSM_dinamico_e IS
   PORT( 
      activa_led_e : OUT    std_logic
   );

-- Declarations

END tb_FSM_dinamico_e ;

--
-- VHDL Architecture tb_dinamico_e.tb_FSM_dinamico_e.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:25:42 13/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY FSM_dinamico_e;

ARCHITECTURE struct OF tb_FSM_dinamico_e IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;
   SIGNAL clk             : std_logic;
   SIGNAL reset_dinamico  : std_logic;
   SIGNAL rst             : std_logic;


   -- Component Declarations
   COMPONENT FSM_dinamico_e
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_e USE ENTITY FSM_dinamico_e.FSM_dinamico_e;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1     
   -- eb1 1                                        
   p_rst : process
   begin
     rst <= '0';
     wait for 30 ns;
     rst <= '1';
     wait for 20 ns;
     rst <= '0';
     wait;
   end process p_rst;    
   
   p_clk : process
   begin
     clk <= '0';
     wait for 5 ns;
     clk <= '1';
     wait for 5 ns;
   end process p_clk;       
                                 
   p_activa_dinamico : process
   begin
       activa_dinamico<='0';
       reset_dinamico <='0';
       wait for 100 ns;
       reset_dinamico<='1';
       wait for 10 ns;
       reset_dinamico <='0';
       wait for 100 ns;
       activa_dinamico<='1';
       wait for 10 ns;
       activa_dinamico<='0';
       wait for 400000000 ns;
       reset_dinamico<='1';
       wait for 10 ns;
       reset_dinamico <='0';
       wait for 100 ns;
       activa_dinamico<='1';
       wait for 10 ns;
       activa_dinamico<='0';
       wait;
     
   end process p_activa_dinamico;
   
   
   


   -- Instance port mappings.
   i_FSM_dinamico_e : FSM_dinamico_e
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         reset_dinamico  => reset_dinamico,
         rst             => rst,
         activa_led_e    => activa_led_e
      );

END struct;
