-- VHDL Entity tb_dinamico_drc_fast.tb_FSM_dinamico_drc_fast.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 07:13:52 12/08/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_FSM_dinamico_drc_fast IS
   PORT( 
      activa_led_w : OUT    std_logic
   );

-- Declarations

END tb_FSM_dinamico_drc_fast ;

--
-- VHDL Architecture tb_dinamico_drc_fast.tb_FSM_dinamico_drc_fast.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 07:36:19 12/08/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY dinamico_drc_fast;

ARCHITECTURE struct OF tb_FSM_dinamico_drc_fast IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;
   SIGNAL clk             : std_logic;
   SIGNAL rst             : std_logic;


   -- Component Declarations
   COMPONENT FSM_dinamico_drc_fast
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_drc_fast USE ENTITY dinamico_drc_fast.FSM_dinamico_drc_fast;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1     
   -- eb1 1                                        
   p_rst : process
   begin
     rst <= '0';
     wait for 1 ns;
     rst <= '1';
     wait for 250 ns;
     rst <= '0';
     wait;
   end process p_rst;    
   
   p_clk : process
   begin
     clk <= '0';
     wait for 50 ns;
     clk <= '1';
     wait for 50 ns;
   end process p_clk;       
   
   
                                 
   p_activa_dinamico : process
   begin
   
     wait for 245 ns;
     activa_dinamico<='1';
     wait for 100 ns;
     activa_dinamico<='0';
     
   end process p_activa_dinamico;


   -- Instance port mappings.
   i_FSM_dinamico_drc_fast : FSM_dinamico_drc_fast
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         rst             => rst,
         activa_led_w    => activa_led_w
      );

END struct;
