-- VHDL Entity FSM_dinamico_w.dinamico_st_todo_w.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:52:41 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY dinamico_st_todo_w IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END dinamico_st_todo_w ;

--
-- VHDL Architecture FSM_dinamico_w.dinamico_st_todo_w.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:52:41 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_w;

ARCHITECTURE struct OF dinamico_st_todo_w IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico_reg : std_logic;
   SIGNAL activa_led_w_aux    : std_logic;
   SIGNAL estado_aux          : std_logic_vector(1 DOWNTO 0);
   SIGNAL reset_dinamico_reg  : std_logic;


   -- Component Declarations
   COMPONENT dinamico_estado_w
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_w    : OUT    std_logic ;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registro_2
   PORT (
      clk : IN     std_logic;
      d   : IN     std_logic_vector (1 DOWNTO 0);
      rst : IN     std_logic;
      q   : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registro_w
   PORT (
      clk : IN     std_logic;
      d   : IN     std_logic;
      rst : IN     std_logic;
      q   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dinamico_estado_w USE ENTITY FSM_dinamico_w.dinamico_estado_w;
   FOR ALL : registro_2 USE ENTITY FSM_dinamico_w.registro_2;
   FOR ALL : registro_w USE ENTITY FSM_dinamico_w.registro_w;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'i_gnd' of 'gnd'
   activa_led_e <= '0';

   -- Instance port mappings.
   i_dinamico_estado_w : dinamico_estado_w
      PORT MAP (
         activa_dinamico => activa_dinamico_reg,
         clk             => clk,
         reset_dinamico  => reset_dinamico_reg,
         rst             => rst,
         activa_led_w    => activa_led_w_aux,
         estado          => estado_aux
      );
   i_reg_estado : registro_2
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => estado_aux,
         q   => estado
      );
   i_reg_activa_dinamico : registro_w
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_dinamico,
         q   => activa_dinamico_reg
      );
   i_reg_activa_led : registro_w
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_led_w_aux,
         q   => activa_led_w
      );
   i_reg_reset_dinamico : registro_w
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => reset_dinamico,
         q   => reset_dinamico_reg
      );

END struct;
