-- VHDL Entity FSM_dinamico_w.implementado_w.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:19:41 20/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY implementado_w IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic
   );

-- Declarations

END implementado_w ;

--
-- VHDL Architecture FSM_dinamico_w.implementado_w.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:19:41 20/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_w;

ARCHITECTURE struct OF implementado_w IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT FSM_dinamico_w_dinamico
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_w_dinamico USE ENTITY FSM_dinamico_w.FSM_dinamico_w_dinamico;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : FSM_dinamico_w_dinamico
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         reset_dinamico  => reset_dinamico,
         rst             => rst,
         activa_led_e    => activa_led_e,
         activa_led_w    => activa_led_w
      );

END struct;
