-- VHDL Entity todo.black_box.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 10:28:00 15/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY black_box IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic
   );

-- Declarations

END black_box ;

--
-- VHDL Architecture todo.black_box.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:58:15 17/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ARCHITECTURE struct OF black_box IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
