-- VHDL Entity todo.genera_trigger.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:49:56 17/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY genera_trigger IS
   PORT( 
      clk       : IN     std_logic;
      rst       : IN     std_logic;
      trigger_e : OUT    std_logic;
      trigger_w : OUT    std_logic
   );

-- Declarations

END genera_trigger ;

--
-- VHDL Architecture todo.genera_trigger.fsm
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:50:03 17/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF genera_trigger IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s4,
      s3
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(30 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(30 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s1 : std_logic;
   SIGNAL csm_to_s2 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk
   )
   -----------------------------------------------------------------
   BEGIN
      IF (clk'EVENT AND clk = '1') THEN
         IF (rst = '1') THEN
            current_state <= s0;
            csm_timer <= (OTHERS => '0');
         ELSE
            current_state <= next_state;
            csm_timer <= csm_next_timer;
         END IF;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s1 <= '0';
      csm_to_s2 <= '0';
      CASE current_state IS
         WHEN s0 => 
            next_state <= s1;
            csm_to_s1 <= '1';
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s3;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s4;
            ELSE
               next_state <= s2;
            END IF;
         WHEN s4 => 
            next_state <= s1;
            csm_to_s1 <= '1';
         WHEN s3 => 
            next_state <= s2;
            csm_to_s2 <= '1';
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      trigger_e <= '0';
      trigger_w <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN s4 => 
            trigger_e<='1';
         WHEN s3 => 
            trigger_w<='1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s1,
      csm_to_s2
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s1 = '1') THEN
         csm_next_timer <= "1100110011001100110011001100101"; -- no cycles(1717986918)-1=1717986917
      ELSIF (csm_to_s2 = '1') THEN
         csm_next_timer <= "1100110011001100110011001100101"; -- no cycles(1717986918)-1=1717986917
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= std_logic_vector(unsigned(csm_timer) - 1);
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
