-- VHDL Entity todo.todo.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 15:43:17 05/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY todo IS
   PORT( 
      clk        : IN     std_logic;
      rst        : IN     std_logic;
      start      : IN     std_logic;
      GPIO_LED_E : OUT    std_logic;
      GPIO_LED_N : OUT    std_logic;
      GPIO_LED_W : OUT    std_logic
   );

-- Declarations

END todo ;

--
-- VHDL Architecture todo.todo.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 15:43:17 05/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY dinamico_drc_fast;
LIBRARY dinamico_iz_slow;
LIBRARY estatico;

ARCHITECTURE struct OF todo IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;


   -- Component Declarations
   COMPONENT FSM_dinamico_drc_fast
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FSM_dinamico_iz_slow
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FSM_estatico
   PORT (
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      start           : IN     std_logic ;
      activa_dinamico : OUT    std_logic ;
      activa_led_n    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_drc_fast USE ENTITY dinamico_drc_fast.FSM_dinamico_drc_fast;
   FOR ALL : FSM_dinamico_iz_slow USE ENTITY dinamico_iz_slow.FSM_dinamico_iz_slow;
   FOR ALL : FSM_estatico USE ENTITY estatico.FSM_estatico;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   i_FSM_dinamico_drc_fast : FSM_dinamico_drc_fast
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         rst             => rst,
         activa_led_w    => GPIO_LED_W
      );
   i_FSM_diramico_iz_slow : FSM_dinamico_iz_slow
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         rst             => rst,
         activa_led_e    => GPIO_LED_E
      );
   i_FSM_estatico : FSM_estatico
      PORT MAP (
         clk             => clk,
         rst             => rst,
         start           => start,
         activa_dinamico => activa_dinamico,
         activa_led_n    => GPIO_LED_N
      );

END struct;
