-- VHDL Entity todo.top.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 05:59:49 07/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY top IS
   PORT( 
      clk        : IN     std_logic;
      rst        : IN     std_logic;
      start      : IN     std_logic;
      GPIO_LED_E : OUT    std_logic;
      GPIO_LED_N : OUT    std_logic;
      GPIO_LED_W : OUT    std_logic
   );

-- Declarations

END top ;

--
-- VHDL Architecture todo.top.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 05:59:49 07/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY estatico;
LIBRARY todo;

ARCHITECTURE struct OF top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;


   -- Component Declarations
   COMPONENT FSM_estatico
   PORT (
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      start           : IN     std_logic ;
      activa_dinamico : OUT    std_logic ;
      activa_led_n    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT black_box
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_estatico USE ENTITY estatico.FSM_estatico;
   FOR ALL : black_box USE ENTITY todo.black_box;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   i_FSM_estatico : FSM_estatico
      PORT MAP (
         clk             => clk,
         rst             => rst,
         start           => start,
         activa_dinamico => activa_dinamico,
         activa_led_n    => GPIO_LED_N
      );
   i_black_box : black_box
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         rst             => rst,
         activa_led_e    => GPIO_LED_E,
         activa_led_w    => GPIO_LED_W
      );

END struct;
