-- VHDL Entity tb_dinamico_w.tb_dinamico_estado_w.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 15:42:48 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY tb_dinamico_estado_w IS
   PORT( 
      activa_led_w : OUT    std_logic;
      estado       : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END tb_dinamico_estado_w ;

--
-- VHDL Architecture tb_dinamico_w.tb_dinamico_estado_w.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 15:42:48 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_w;

ARCHITECTURE struct OF tb_dinamico_estado_w IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico : std_logic;
   SIGNAL clk             : std_logic;
   SIGNAL reset_dinamico  : std_logic;
   SIGNAL rst             : std_logic;


   -- Component Declarations
   COMPONENT dinamico_estado_w
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_w    : OUT    std_logic ;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dinamico_estado_w USE ENTITY FSM_dinamico_w.dinamico_estado_w;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   
   -- eb1 1                                        
   p_clk: process
   begin
       clk<='0';
       wait for 5 ns;
       clk<='1' ;
       wait for 5 ns;
   end process p_clk;
   
   p_rst: process
   begin
       rst<='0';
       wait for 50 ns;
       rst<='1';
       wait for 10 ns;
       rst<='0';
       wait;
   end process;
   
   p_reset_dinamico:process
   begin
       reset_dinamico<='0';
       activa_dinamico<='0';
       wait for 100 ns;
       
       reset_dinamico<='1';
       activa_dinamico<='0';
       wait for 10 ns;
       
       reset_dinamico<='0';
       activa_dinamico<='0';
       wait for 100 ns;
       
       reset_dinamico<='0';
       activa_dinamico<='1';
       wait for 10 ns;
       
       reset_dinamico<='0';
       activa_dinamico<='0';
       wait;
   end process;
       


   -- Instance port mappings.
   U_0 : dinamico_estado_w
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk,
         reset_dinamico  => reset_dinamico,
         rst             => rst,
         activa_led_w    => activa_led_w,
         estado          => estado
      );

END struct;
