-- VHDL Entity tb_todo.tb_divisor_frecuencia.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 12:36:42 18/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY tb_divisor_frecuencia IS
   PORT( 
      clk_100mz : OUT    std_logic
   );

-- Declarations

END tb_divisor_frecuencia ;

--
-- VHDL Architecture tb_todo.tb_divisor_frecuencia.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 12:36:42 18/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY todo;

ARCHITECTURE struct OF tb_divisor_frecuencia IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_200mz : std_logic;
   SIGNAL rst       : std_logic;


   -- Component Declarations
   COMPONENT divisor_frecuencia
   PORT (
      clk_200mz : IN     std_logic;
      rst       : IN     std_logic;
      clk_100mz : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : divisor_frecuencia USE ENTITY todo.divisor_frecuencia;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   p_clk : process
   begin
     clk_200mz <= '0';
     wait for 5 ns;
     clk_200mz <= '1';
     wait for 5 ns;
   end process p_clk;  
   
   p_rst:process
   begin
   rst<='0';
   wait for 40 ns;
   rst<='1';
   wait for 40ns;
   rst<='0';
   wait;
   end process;
   
   


   -- Instance port mappings.
   U_0 : divisor_frecuencia
      PORT MAP (
         clk_200mz => clk_200mz,
         rst       => rst,
         clk_100mz => clk_100mz
      );

END struct;
