-- VHDL Entity tb_todo.tb_inversion.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:21:50 03/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY tb_inversion IS
   PORT( 
      out_invertida : OUT    std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END tb_inversion ;

--
-- VHDL Architecture tb_todo.tb_inversion.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:30:44 03/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_todo;
LIBRARY todo;

ARCHITECTURE struct OF tb_inversion IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL I   : std_logic_vector(31 DOWNTO 0);
   SIGNAL clk : std_logic;


   -- Component Declarations
   COMPONENT tester_generico
   PORT (
      clk : IN     std_logic ;
      I   : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT inversion
   PORT (
      entrada       : IN     std_logic_vector (31 DOWNTO 0);
      out_invertida : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : inversion USE ENTITY todo.inversion;
   FOR ALL : tester_generico USE ENTITY tb_todo.tester_generico;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
      
   
   p_clk : process
   begin
     clk <= '0';
     wait for 10 ns;
     clk <= '1';
     wait for 10 ns;
   end process p_clk;  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   


   -- Instance port mappings.
   i_tester : tester_generico
      PORT MAP (
         clk => clk,
         I   => I
      );
   U_0 : inversion
      PORT MAP (
         entrada       => I,
         out_invertida => out_invertida
      );

END struct;
