-- VHDL Entity tb_todo.tb_todo.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:58:15 05/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_todo IS
   PORT( 
      activa_led_e : OUT    std_logic;
      activa_led_n : OUT    std_logic;
      activa_led_w : OUT    std_logic
   );

-- Declarations

END tb_todo ;

--
-- VHDL Architecture tb_todo.tb_todo.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 08:58:15 05/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY todo;

ARCHITECTURE struct OF tb_todo IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL rst   : std_logic;
   SIGNAL start : std_logic;


   -- Component Declarations
   COMPONENT todo
   PORT (
      clk        : IN     std_logic ;
      rst        : IN     std_logic ;
      start      : IN     std_logic ;
      GPIO_LED_E : OUT    std_logic ;
      GPIO_LED_N : OUT    std_logic ;
      GPIO_LED_W : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : todo USE ENTITY todo.todo;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1   
   -- eb1 1      
   p_rst : process
   begin
     rst <= '0';
     wait for 1 ns;
     rst <= '1';
     wait for 250 ns;
     rst <= '0';
     wait;
   end process p_rst;    
   
   p_clk : process
   begin
     clk <= '0';
     wait for 50 ns;
     clk <= '1';
     wait for 50 ns;
   end process p_clk;  
   
   p_start : process
   begin
     start <= '0';
     wait for 500 ns;
     start <= '1';
     wait for 250 ns;
     start <= '0';
     wait;
   end process p_start;   
        
   
   
                                 
                                          
   
   
   
   
   


   -- Instance port mappings.
   i_todo : todo
      PORT MAP (
         clk        => clk,
         rst        => rst,
         start      => start,
         GPIO_LED_E => activa_led_e,
         GPIO_LED_N => activa_led_n,
         GPIO_LED_W => activa_led_w
      );

END struct;
