-- VHDL Entity tb_icap.tb_icap.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 09:41:00 13/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY UNISIM;
USE UNISIM.vcomponents.ALL;

ENTITY tb_icap IS
   PORT( 
      BUSY : OUT    std_ulogic  := '1';
      O    : OUT    std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END tb_icap ;

--
-- VHDL Architecture tb_icap.tb_icap.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 11:44:11 15/09/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.ALL;
LIBRARY UNISIM;
USE UNISIM.vcomponents.ALL;

LIBRARY tb_icap;

ARCHITECTURE struct OF tb_icap IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CLK      : std_logic;
   SIGNAL CSB      : std_logic;
   SIGNAL RDWRB    : std_logic;
   SIGNAL capacita : std_logic;
   SIGNAL i        : std_logic_vector(31 DOWNTO 0);


   -- Component Declarations
   COMPONENT tester_generico
   PORT (
      CLK      : IN     std_logic ;
      capacita : IN     std_logic ;
      i        : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tester_generico USE ENTITY tb_icap.tester_generico;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
      
   
   p_clk : process
   begin
     clk <= '0';
     wait for 10 ns;
     clk <= '1';
     wait for 10 ns;
   end process p_clk;  
   
   p_csb : process
   begin
     csb <= '0';
     wait for 2700 ns;
     csb <= '0';
     wait;
   end process p_csb; 
   
   p_RDWRB : process
   begin
     RDWRB <= '0';
     wait for 2650 ns;
     RDWRB <= '0';
     wait;
   end process p_RDWRB; 
   
   
   
   p_capacita : process
   begin
     capacita <= '0';
     wait for 2040 ns;
     capacita <= '1';
     wait;
   end process p_capacita; 
   
   
   
   
   
   
   
   
   
   
   
   
   
   

   -- HDL Embedded Text Block 2 eb2
   
   
   
   ICAP_VIRTEX6_inst  :  ICAP_VIRTEX6
   generic  map  (
   DEVICE_ID  =>  X"04250093", --  Specifies  the  pre-programmed  Device  ID  value
   ICAP_WIDTH  =>  "X8", --  Specifies  the  input  and  output  data  width  to  be  used  with  the
   --  ICAP_VIRTEX6.
   SIM_CFG_FILE_NAME  =>  "T:\Reconfiguracion_Dinamica\sim\simula.rbt"    --  Specifies  the  Raw  Bitstream  (RBT)  file  to  be  parsed  by  the  simulation
   --  model
   --SIM_CFG_FILE_NAME  =>  "none"
   
   
   )
   port  map  (
   BUSY  =>  BUSY,      --  1-bit  Busy/Ready  output
   O  =>  O, --  32-bit  Configuration  data  output  bus
   CLK  =>  CLK, --  1-bit  Clock  Input
   CSB  =>  CSB, --  1-bit  Active-Low  ICAP  input  Enable
   I  =>  I, --  32-bit  Configuration  data  input  bus
   RDWRB  =>  RDWRB    --  1-bit  Read/Write  Select  input
   );
   --  End  of  ICAP_VIRTEX6_inst  instantiation                                  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   


   -- Instance port mappings.
   i_tester : tester_generico
      PORT MAP (
         CLK      => CLK,
         capacita => capacita,
         i        => i
      );

END struct;
