-- VHDL Entity FSM_dinamico_e.dinamico_e.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 10:22:06 15/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std;

ENTITY dinamico_e IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic
   );

-- Declarations

END dinamico_e ;

--
-- VHDL Architecture FSM_dinamico_e.dinamico_e.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 10:22:45 30/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_e;

ARCHITECTURE struct OF dinamico_e IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico_reg : std_logic;
   SIGNAL activa_led_e_aux    : std_logic;
   SIGNAL reset_dinamico_reg  : std_logic;


   -- Component Declarations
   COMPONENT dinamico_fsm_e
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT registro_e
   PORT (
      clk : IN     std_logic;
      d   : IN     std_logic;
      rst : IN     std_logic;
      q   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dinamico_fsm_e USE ENTITY FSM_dinamico_e.dinamico_fsm_e;
   FOR ALL : registro_e USE ENTITY FSM_dinamico_e.registro_e;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'gnd'
   activa_led_w <= '0';

   -- Instance port mappings.
   i_FSM_dinamico_e : dinamico_fsm_e
      PORT MAP (
         activa_dinamico => activa_dinamico_reg,
         clk             => clk,
         reset_dinamico  => reset_dinamico_reg,
         rst             => rst,
         activa_led_e    => activa_led_e_aux
      );
   i_Act_din : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_dinamico,
         q   => activa_dinamico_reg
      );
   i_activa_led : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_led_e_aux,
         q   => activa_led_e
      );
   i_reg_rst_din : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => reset_dinamico,
         q   => reset_dinamico_reg
      );

END struct;
