-- VHDL Entity FSM_dinamico_e.dinamico_st_todo_e.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:35:38 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY dinamico_st_todo_e IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END dinamico_st_todo_e ;

--
-- VHDL Architecture FSM_dinamico_e.dinamico_st_todo_e.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 17:35:38 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_e;

ARCHITECTURE struct OF dinamico_st_todo_e IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL activa_dinamico_reg : std_logic;
   SIGNAL activa_led_e_aux    : std_logic;
   SIGNAL estado_aux          : std_logic_vector(1 DOWNTO 0);
   SIGNAL reset_dinamico_reg  : std_logic;


   -- Component Declarations
   COMPONENT dinamico_estado_e
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic ;
      estado          : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registro_2
   PORT (
      clk : IN     std_logic;
      d   : IN     std_logic_vector (1 DOWNTO 0);
      rst : IN     std_logic;
      q   : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registro_e
   PORT (
      clk : IN     std_logic;
      d   : IN     std_logic;
      rst : IN     std_logic;
      q   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dinamico_estado_e USE ENTITY FSM_dinamico_e.dinamico_estado_e;
   FOR ALL : registro_2 USE ENTITY FSM_dinamico_e.registro_2;
   FOR ALL : registro_e USE ENTITY FSM_dinamico_e.registro_e;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'i_gnd' of 'gnd'
   activa_led_w <= '0';

   -- Instance port mappings.
   i_dinamico_estado_e : dinamico_estado_e
      PORT MAP (
         activa_dinamico => activa_dinamico_reg,
         clk             => clk,
         reset_dinamico  => reset_dinamico_reg,
         rst             => rst,
         activa_led_e    => activa_led_e_aux,
         estado          => estado_aux
      );
   i_reg_estado : registro_2
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => estado_aux,
         q   => estado
      );
   i_reg_activa_dinamico : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_dinamico,
         q   => activa_dinamico_reg
      );
   i_reg_activa_led_e : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => activa_led_e_aux,
         q   => activa_led_e
      );
   i_reg_reset_dinamico : registro_e
      PORT MAP (
         clk => clk,
         rst => rst,
         d   => reset_dinamico,
         q   => reset_dinamico_reg
      );

END struct;
