-- VHDL Entity FSM_dinamico_e.implementado_e.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:50:04 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY implementado_e IS
   PORT( 
      activa_dinamico : IN     std_logic;
      clk             : IN     std_logic;
      reset_dinamico  : IN     std_logic;
      rst             : IN     std_logic;
      activa_led_e    : OUT    std_logic;
      activa_led_w    : OUT    std_logic
   );

-- Declarations

END implementado_e ;

--
-- VHDL Architecture FSM_dinamico_e.implementado_e.struct
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 16:50:04 27/10/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.1b (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY FSM_dinamico_e;
LIBRARY todo;

ARCHITECTURE struct OF implementado_e IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_100mz : std_logic;


   -- Component Declarations
   COMPONENT FSM_dinamico_e_dinamico
   PORT (
      activa_dinamico : IN     std_logic ;
      clk             : IN     std_logic ;
      reset_dinamico  : IN     std_logic ;
      rst             : IN     std_logic ;
      activa_led_e    : OUT    std_logic ;
      activa_led_w    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT divisor_frecuencia
   PORT (
      clk_200mz : IN     std_logic;
      clk_100mz : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_dinamico_e_dinamico USE ENTITY FSM_dinamico_e.FSM_dinamico_e_dinamico;
   FOR ALL : divisor_frecuencia USE ENTITY todo.divisor_frecuencia;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : FSM_dinamico_e_dinamico
      PORT MAP (
         activa_dinamico => activa_dinamico,
         clk             => clk_100mz,
         reset_dinamico  => reset_dinamico,
         rst             => rst,
         activa_led_e    => activa_led_e,
         activa_led_w    => activa_led_w
      );
   U_1 : divisor_frecuencia
      PORT MAP (
         clk_200mz => clk,
         clk_100mz => clk_100mz
      );

END struct;
